# Generated by Django 6.0.2 on 2026-03-04 15:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('level', models.CharField(blank=True, choices=[('premed', 'Pre-Med Foundation'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('moderator', 'Moderator'), ('senior_moderator', 'Senior Moderator'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('premed_cohort', models.CharField(blank=True, max_length=20)),
                ('intended_programme', models.CharField(blank=True, max_length=100)),
                ('upload_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('moderator_seat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(help_text='Unique code for this seat (e.g., MBBS-3-REP-1)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., MBBS Year 3 Rep', max_length=100)),
                ('seat_type', models.CharField(choices=[('class_rep', '👑 Class Representative'), ('assistant', '🤝 Assistant Representative'), ('subject_lead', '📚 Subject Lead')], default='class_rep', max_length=20)),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('programme_code', models.CharField(blank=True, help_text='e.g., MBBS, BNS, BPHARM', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('holder_history', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacant', 'Vacant'), ('suspended', 'Suspended')], default='vacant', max_length=20)),
                ('term_start', models.DateField(auto_now_add=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('last_transferred', models.DateTimeField(blank=True, null=True)),
                ('transfer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'programme', 'year', 'seat_type'],
                'unique_together': {('level', 'school', 'programme', 'year', 'seat_type', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('handout', '📄 Handout'), ('past_paper', '📝 Past Paper'), ('lecture_note', '📚 Lecture Note'), ('research', '🔬 Research Article'), ('clinical_guide', '🩺 Clinical Guide'), ('video', '🎥 Video'), ('study_set', '📋 Study Set'), ('summary', '📊 Summary Sheet'), ('lab_manual', '🧪 Lab Manual'), ('case_study', '🏥 Case Study'), ('formula_sheet', '📐 Formula Sheet'), ('diagram', '📊 Diagram')], max_length=20)),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('premed_subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/')),
                ('video_link', models.URLField(blank=True, help_text='YouTube/Vimeo link for video resources', null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resources', to=settings.AUTH_USER_MODEL)),
                ('is_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text="Describe exactly what you're looking for")),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('premed_subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', '🟢 Open'), ('in_progress', '🟡 In Progress'), ('fulfilled', '✅ Fulfilled'), ('closed', '🔴 Closed')], default='open', max_length=20)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority (moderator only)')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important requests')),
                ('moderator_notes', models.TextField(blank=True, help_text='Internal moderator notes')),
                ('urgency', models.CharField(choices=[('urgent', '🔴 Urgent'), ('high', '🟠 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='core.resource')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_by', to='core.resourcerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request_created', '📝 Request Created'), ('request_updated', '🔄 Request Updated'), ('request_fulfilled', '✅ Request Fulfilled'), ('request_upvoted', '👍 Request Upvoted'), ('resource_approved', '✅ Resource Approved'), ('resource_rejected', '❌ Resource Rejected'), ('resource_uploaded', '📤 Resource Uploaded'), ('resource_downloaded', '📥 Resource Downloaded'), ('comment_added', '💬 Comment Added'), ('moderator_action', '🛡️ Moderator Action'), ('system_announcement', '📢 Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.resource')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.resourcerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('expired', '⌛ Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.moderatorseat')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'upload_date'], name='core_resour_status_8a9884_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['level', 'premed_subject'], name='core_resour_level_e4f926_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['school', 'programme', 'year_of_study'], name='core_resour_school_4d1257_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'resource')},
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', 'created_at'], name='core_resour_status_3f7cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['level', 'premed_subject'], name='core_resour_level_4ce5f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestupvote',
            unique_together={('user', 'request')},
        ),
    ]
