# Generated by Django 6.0.2 on 2026-03-02 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailverification_token_alter_user_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('handout', '📄 Handout'), ('past_paper', '📝 Past Paper'), ('lecture_note', '📚 Lecture Note'), ('research', '🔬 Research Article'), ('clinical_guide', '🩺 Clinical Guide'), ('video', '🎥 Video'), ('study_set', '📋 Study Set'), ('summary', '📊 Summary Sheet'), ('lab_manual', '🧪 Lab Manual'), ('case_study', '🏥 Case Study'), ('formula_sheet', '📐 Formula Sheet'), ('diagram', '📊 Diagram')], max_length=20)),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('premed_subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('file', models.FileField(upload_to='resources/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resources', to=settings.AUTH_USER_MODEL)),
                ('is_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('premed_subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'upload_date'], name='core_resour_status_8a9884_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['level', 'premed_subject'], name='core_resour_level_e4f926_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['school', 'programme', 'year_of_study'], name='core_resour_school_4d1257_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'resource')},
        ),
    ]
