# Generated by Django 6.0.2 on 2026-03-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resource_rating_bookmark_resourcerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link for video resources', null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/'),
        ),
    ]
