# Generated by Django 6.0.2 on 2026-03-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_video_link_alter_emailverification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resourcerequest',
            options={'ordering': ['-upvotes', '-created_at']},
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='course_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='urgency',
            field=models.CharField(choices=[('urgent', '🔴 Urgent'), ('high', '🟠 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='description',
            field=models.TextField(help_text="Describe exactly what you're looking for"),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='core.resource'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('open', '🟢 Open'), ('in_progress', '🟡 In Progress'), ('fulfilled', '✅ Fulfilled'), ('closed', '🔴 Closed')], default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', 'created_at'], name='core_resour_status_3f7cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['level', 'premed_subject'], name='core_resour_level_4ce5f6_idx'),
        ),
        migrations.AddField(
            model_name='requestupvote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_by', to='core.resourcerequest'),
        ),
        migrations.AddField(
            model_name='requestupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='requestupvote',
            unique_together={('user', 'request')},
        ),
    ]
