# Generated by Django 6.0.2 on 2026-03-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requestupvote_alter_resourcerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin important requests'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Internal moderator notes'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority (moderator only)'),
        ),
    ]
