# Generated by Django 6.0.2 on 2026-03-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resourcerequest_is_pinned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request_created', '📝 Request Created'), ('request_updated', '🔄 Request Updated'), ('request_fulfilled', '✅ Request Fulfilled'), ('request_upvoted', '👍 Request Upvoted'), ('resource_approved', '✅ Resource Approved'), ('resource_rejected', '❌ Resource Rejected'), ('resource_uploaded', '📤 Resource Uploaded'), ('resource_downloaded', '📥 Resource Downloaded'), ('comment_added', '💬 Comment Added'), ('moderator_action', '🛡️ Moderator Action'), ('system_announcement', '📢 Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.resourcerequest')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
