# Generated by Django 6.0.2 on 2026-03-03 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., MBBS Year 3 Rep', max_length=100)),
                ('seat_type', models.CharField(choices=[('class_rep', '👑 Class Representative'), ('assistant', '🤝 Assistant Representative'), ('subject_lead', '📚 Subject Lead')], default='class_rep', max_length=20)),
                ('level', models.CharField(choices=[('premed', 'Pre-Med'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], max_length=20)),
                ('school', models.CharField(blank=True, choices=[('medicine', 'Medicine and Oral Health'), ('nursing', 'Nursing'), ('maternal', 'Maternal, Neonatal and Reproductive Health'), ('life_sciences', 'Life Sciences and Allied Health Professions'), ('public_health', 'Global and Public Health')], max_length=20, null=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('biology', '🧬 Biology'), ('chemistry', '🧪 Chemistry'), ('physics', '⚡ Physics'), ('mathematics', '📐 Mathematics'), ('ict', '💻 ICT'), ('communication', '🗣️ Communication')], max_length=20, null=True)),
                ('holder_history', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacant', 'Vacant'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('term_start', models.DateField(auto_now_add=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('last_transferred', models.DateTimeField(blank=True, null=True)),
                ('transfer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'programme', 'year'],
                'unique_together': {('level', 'school', 'programme', 'year', 'seat_type', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('expired', '⌛ Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.moderatorseat')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
