# Generated by Django 6.0.2 on 2026-03-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_moderatorseat_transferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderatorseat',
            options={'ordering': ['level', 'programme', 'year', 'seat_type']},
        ),
        migrations.AddField(
            model_name='moderatorseat',
            name='programme_code',
            field=models.CharField(blank=True, help_text='e.g., MBBS, BNS, BPHARM', max_length=20),
        ),
        migrations.AddField(
            model_name='moderatorseat',
            name='seat_code',
            field=models.CharField(default='TEMP-SEAT', help_text='Unique code for this seat (e.g., MBBS-3-REP-1)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moderatorseat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('vacant', 'Vacant'), ('suspended', 'Suspended')], default='vacant', max_length=20),
        ),
    ]
