from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('verify-email/<uuid:token>/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<uuid:token>/', views.reset_password, name='reset_password'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('download/<int:resource_id>/', views.download_resource, name='download_resource'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('upload/', views.upload_resource, name='upload_resource'),
    path('my-uploads/', views.my_uploads, name='my_uploads'),
    path('browse/', views.browse_resources, name='browse_resources'),
    path('moderator/', views.moderator_dashboard, name='moderator_dashboard'),
    path('moderator/approve/<int:resource_id>/', views.approve_resource, name='approve_resource'),
    path('moderator/reject/<int:resource_id>/', views.reject_resource, name='reject_resource'),
    path('moderator/bulk-approve/', views.bulk_approve, name='bulk_approve'),
    path('requests/', views.request_list, name='request_list'),
    path('requests/create/', views.create_request, name='create_request'),
    path('requests/<int:request_id>/', views.request_detail, name='request_detail'),
    path('requests/<int:request_id>/upvote/', views.upvote_request, name='upvote_request'),
    path('requests/<int:request_id>/fulfill/', views.mark_fulfilled, name='mark_fulfilled'),
    path('requests/<int:request_id>/moderate/', views.moderate_request, name='moderate_request'),
    path('analytics/', views.analytics_dashboard, name='analytics_dashboard'),
    path('my-requests/', views.my_requests, name='my_requests'),
    path('moderator/seats/', views.class_rep_dashboard, name='class_rep_dashboard'),
    path('resource/<int:resource_id>/bookmark/', views.toggle_bookmark, name='toggle_bookmark'),
    path('bookmarks/', views.my_bookmarks, name='my_bookmarks'),
    path('resource/<int:resource_id>/rate/', views.rate_resource, name='rate_resource'),
    path('moderator/seats/create/', views.create_seat, name='create_seat'),
    path('moderator/seats/<int:seat_id>/transfer/', views.initiate_transfer, name='initiate_transfer'),
    path('moderator/transfers/', views.my_transfers, name='my_transfers'),
    path('moderator/transfers/<int:transfer_id>/respond/', views.respond_transfer, name='respond_transfer'),
    path('toast-demo/', views.toast_demo, name='toast_demo'),
    path('ajax-toast/', views.ajax_toast, name='ajax_toast'),
    path('moderator/transfers/<int:transfer_id>/approve/', views.approve_transfer, name='approve_transfer'),
    path('resource/<int:resource_id>/delete/', views.delete_resource, name='delete_resource'),
    path('request/<int:request_id>/delete/', views.delete_request, name='delete_request'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('resource/<int:resource_id>/', views.resource_detail, name='resource_detail'),
]